//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_option
    {
        public int question_option_id { get; set; }
        public int question_def_id { get; set; }
        public string option_text { get; set; }
        public string option_description { get; set; }
        public Nullable<int> option_value { get; set; }
    
        public virtual question_def QuestionDef { get; set; }
    }
}
