//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyTestEntities : DbContext
    {
        public SurveyTestEntities()
            : base("name=SurveyTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<question_def> question_def { get; set; }
        public DbSet<question_format> question_format { get; set; }
        public DbSet<survey> surveys { get; set; }
        public DbSet<survey_answer> survey_answer { get; set; }
        public DbSet<survey_question> survey_question { get; set; }
        public DbSet<survey_response> survey_response { get; set; }
    }
}
