//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_question
    {
        public int survey_question_id { get; set; }
        public int survey_id { get; set; }
        public int question_def_id { get; set; }
        public string question_def_description { get; set; }
        public int question_order { get; set; }
        public Nullable<bool> mandatory { get; set; }
    
        public virtual question_def QuestionDef { get; set; }
        public virtual survey Survey { get; set; }
    }
}
