//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_response
    {
        public survey_response()
        {
            this.SurveyAnswers = new HashSet<survey_answer>();
        }
    
        public int survey_response_id { get; set; }
        public int survey_id { get; set; }
        public System.DateTime date_taken { get; set; }
        public string person_name { get; set; }
        public string email_address { get; set; }
        public Nullable<int> response_total_value { get; set; }
    
        public virtual survey Survey { get; set; }
        public virtual ICollection<survey_answer> SurveyAnswers { get; set; }
    }
}
