//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        public survey()
        {
            this.SurveyQuestions = new HashSet<survey_question>();
        }
    
        public int survey_id { get; set; }
        public string survey_name { get; set; }
        public string survey_desc { get; set; }
    
        public virtual ICollection<survey_question> SurveyQuestions { get; set; }
    }
}
