//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTest.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_answer
    {
        public int survey_answer_id { get; set; }
        public int survey_response_id { get; set; }
        public int survey_question_id { get; set; }
        public string survey_answer1 { get; set; }
    
        public virtual survey_response survey_response { get; set; }
        public virtual survey_question survey_question { get; set; }
    }
}
